/**
 * Emails each student's progress-report PDF to their parent(s).
 *
 * Expects:
 *  - A Google Drive folder containing the PDFs generated by the Python
 *    project, named "studentId_LastName_FirstName.pdf" (that exact
 *    format -- this script matches on the digits before the first "_").
 *  - A sheet (tab) named "Reports" with a header row containing at
 *    least: student_id, parent1_email
 *    Optional columns: parent2_email, student_name, status
 *    (status is written by this script -- add it yourself or it will
 *    be created for you the first time you run Preview/Send.)
 *
 * Setup: fill in the CONFIG block below, then reload the spreadsheet --
 * a "Progress Reports" menu will appear. See google_apps_script/README.md
 * for the full walkthrough.
 */

const CONFIG = {
  // The Drive folder ID containing the PDFs (from the folder's URL:
  // https://drive.google.com/drive/folders/<THIS PART>).
  DRIVE_FOLDER_ID: 'PUT_YOUR_DRIVE_FOLDER_ID_HERE',

  // Name of the sheet/tab with your student_id -> parent email rows.
  SHEET_NAME: 'Reports',

  // Used in the email subject/body. {{studentName}} is replaced with
  // the student_name column if present, otherwise the student id.
  SCHOOL_NAME: 'Your School',
  EMAIL_SUBJECT: 'Mid-Term Progress Report -- {{studentName}}',
  EMAIL_BODY:
    'Hello,\n\n' +
    'Attached is the mid-term progress report for {{studentName}}.\n\n' +
    'Please reach out to the school office with any questions.\n\n' +
    'Thank you,\n' +
    '{{schoolName}}',

  // Optional: the "From" display name on sent emails (the address
  // itself is always whichever Google account runs the script).
  FROM_NAME: '',
};

const COLUMNS = {
  STUDENT_ID: 'student_id',
  STUDENT_NAME: 'student_name',
  PARENT1_EMAIL: 'parent1_email',
  PARENT2_EMAIL: 'parent2_email',
  STATUS: 'status',
};

const SENT_PREFIX = 'SENT';

// ---------------------------------------------------------------------
// Menu
// ---------------------------------------------------------------------

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('Progress Reports')
    .addItem('Preview (dry run)', 'previewSend')
    .addItem('Send Reports', 'sendReportsWithConfirmation')
    .addSeparator()
    .addItem('Reset status column (clears send history)', 'resetStatusColumn')
    .addToUi();
}

function previewSend() {
  runBatch({ dryRun: true });
}

function sendReportsWithConfirmation() {
  const ui = SpreadsheetApp.getUi();
  const { toSend, alreadySent, errors } = planBatch();

  if (toSend.length === 0) {
    ui.alert(
      'Nothing to send',
      `No new rows to email. ${alreadySent.length} already sent, ${errors.length} with errors. ` +
        'Run "Preview (dry run)" for details.',
      ui.ButtonSet.OK
    );
    return;
  }

  const quota = MailApp.getRemainingDailyQuota();
  if (quota < toSend.length) {
    ui.alert(
      'Not enough email quota left today',
      `This would send ${toSend.length} emails, but this account only has ${quota} sends left today. ` +
        'Run the remainder tomorrow, or send from a Google Workspace account (higher daily quota).',
      ui.ButtonSet.OK
    );
    return;
  }

  const response = ui.alert(
    'Send progress reports?',
    `This will email ${toSend.length} student(s)'s progress report(s) now. ` +
      `(${alreadySent.length} already sent will be skipped, ${errors.length} have errors and will be skipped.)\n\n` +
      'This cannot be undone. Continue?',
    ui.ButtonSet.YES_NO
  );
  if (response !== ui.Button.YES) return;

  runBatch({ dryRun: false });
}

function resetStatusColumn() {
  const ui = SpreadsheetApp.getUi();
  const response = ui.alert(
    'Reset status column?',
    'This clears every row\'s send status, so the next "Send Reports" run will re-email everyone ' +
      '(including students already emailed). Use this at the start of a new reporting period, not ' +
      'to retry a few failed rows -- fix just those rows\' status cells by hand instead.',
    ui.ButtonSet.YES_NO
  );
  if (response !== ui.Button.YES) return;

  const sheet = getSheet_();
  const { headerRow, colIndex } = readHeader_(sheet);
  const statusCol = colIndex[COLUMNS.STATUS];
  if (!statusCol) return;

  const lastRow = sheet.getLastRow();
  if (lastRow > 1) {
    sheet.getRange(2, statusCol, lastRow - 1, 1).clearContent();
  }
  ui.alert('Status column cleared.');
}

// ---------------------------------------------------------------------
// Core batch logic
// ---------------------------------------------------------------------

/**
 * Classifies every data row without sending anything or writing to the
 * sheet -- used both for the pre-send confirmation dialog and for
 * previewSend's dry run.
 */
function planBatch() {
  const sheet = getSheet_();
  const { colIndex } = readHeader_(sheet);
  const data = sheet.getDataRange().getValues();
  const pdfIndex = buildPdfIndex_();

  const toSend = [];
  const alreadySent = [];
  const errors = [];

  for (let r = 1; r < data.length; r++) {
    const row = data[r];
    const studentId = String(row[colIndex[COLUMNS.STUDENT_ID] - 1] || '').trim();
    if (!studentId) continue; // blank row

    const status = String(row[colIndex[COLUMNS.STATUS] - 1] || '').trim();
    if (status.indexOf(SENT_PREFIX) === 0) {
      alreadySent.push({ rowNum: r + 1, studentId });
      continue;
    }

    const parent1 = String(row[colIndex[COLUMNS.PARENT1_EMAIL] - 1] || '').trim();
    const parent2Col = colIndex[COLUMNS.PARENT2_EMAIL];
    const parent2 = parent2Col ? String(row[parent2Col - 1] || '').trim() : '';
    const nameCol = colIndex[COLUMNS.STUDENT_NAME];
    const studentName = nameCol ? String(row[nameCol - 1] || '').trim() : '';

    if (!parent1) {
      errors.push({ rowNum: r + 1, studentId, reason: `Missing ${COLUMNS.PARENT1_EMAIL}` });
      continue;
    }
    if (!isValidEmail_(parent1) || (parent2 && !isValidEmail_(parent2))) {
      errors.push({ rowNum: r + 1, studentId, reason: 'Malformed email address' });
      continue;
    }

    const file = pdfIndex[studentId];
    if (!file) {
      errors.push({ rowNum: r + 1, studentId, reason: `No PDF found in Drive folder for student ${studentId}` });
      continue;
    }

    toSend.push({ rowNum: r + 1, studentId, studentName, parent1, parent2, file });
  }

  return { toSend, alreadySent, errors };
}

function runBatch({ dryRun }) {
  const sheet = getSheet_();
  const { colIndex } = readHeader_(sheet);
  const statusCol = colIndex[COLUMNS.STATUS];
  const { toSend, errors } = planBatch();

  errors.forEach((e) => {
    sheet.getRange(e.rowNum, statusCol).setValue(`ERROR: ${e.reason}`);
  });

  let sentCount = 0;
  toSend.forEach((item) => {
    if (dryRun) {
      const recipients = item.parent2 ? `${item.parent1}, ${item.parent2}` : item.parent1;
      sheet
        .getRange(item.rowNum, statusCol)
        .setValue(`DRY RUN -- would email ${recipients} (${item.file.getName()})`);
      return;
    }

    try {
      sendOne_(item);
      sheet
        .getRange(item.rowNum, statusCol)
        .setValue(`${SENT_PREFIX} ${Utilities.formatDate(new Date(), Session.getScriptTimeZone(), 'yyyy-MM-dd HH:mm')}`);
      sentCount++;
    } catch (err) {
      sheet.getRange(item.rowNum, statusCol).setValue(`ERROR: ${err.message}`);
    }
  });

  const ui = SpreadsheetApp.getUi();
  if (dryRun) {
    ui.alert(
      'Preview complete',
      `${toSend.length} would be sent, ${errors.length} have errors. See the status column for details.`,
      ui.ButtonSet.OK
    );
  } else {
    ui.alert('Done', `Sent ${sentCount} of ${toSend.length} email(s). See the status column for details.`, ui.ButtonSet.OK);
  }
}

function sendOne_(item) {
  const studentLabel = item.studentName || `student ${item.studentId}`;
  const subject = CONFIG.EMAIL_SUBJECT.replace('{{studentName}}', studentLabel);
  const body = CONFIG.EMAIL_BODY.replace('{{studentName}}', studentLabel).replace('{{schoolName}}', CONFIG.SCHOOL_NAME);

  const options = { attachments: [item.file.getBlob()] };
  if (item.parent2) options.cc = item.parent2;
  if (CONFIG.FROM_NAME) options.name = CONFIG.FROM_NAME;

  GmailApp.sendEmail(item.parent1, subject, body, options);
}

// ---------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------

function getSheet_() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CONFIG.SHEET_NAME);
  if (!sheet) {
    throw new Error(`No sheet named "${CONFIG.SHEET_NAME}" found. Check CONFIG.SHEET_NAME in Code.gs.`);
  }
  return sheet;
}

/** Maps header text -> 1-based column index. Adds a "status" column at
 * the end if one isn't present yet. */
function readHeader_(sheet) {
  const lastCol = sheet.getLastColumn();
  const headerRow = sheet.getRange(1, 1, 1, lastCol).getValues()[0].map((h) => String(h).trim());
  const colIndex = {};
  headerRow.forEach((h, i) => {
    if (h) colIndex[h] = i + 1;
  });

  const required = [COLUMNS.STUDENT_ID, COLUMNS.PARENT1_EMAIL];
  const missing = required.filter((c) => !colIndex[c]);
  if (missing.length) {
    throw new Error(`Sheet "${CONFIG.SHEET_NAME}" is missing required column(s): ${missing.join(', ')}`);
  }

  if (!colIndex[COLUMNS.STATUS]) {
    const newCol = lastCol + 1;
    sheet.getRange(1, newCol).setValue(COLUMNS.STATUS);
    colIndex[COLUMNS.STATUS] = newCol;
  }

  return { headerRow, colIndex };
}

/** Scans the Drive folder once and indexes files by the studentId
 * prefix in their filename (studentId_LastName_FirstName.pdf). If two
 * files share a student id, the most recently updated one wins. */
function buildPdfIndex_() {
  const folder = DriveApp.getFolderById(CONFIG.DRIVE_FOLDER_ID);
  const files = folder.getFilesByType(MimeType.PDF);
  const index = {};

  while (files.hasNext()) {
    const file = files.next();
    const match = file.getName().match(/^(\d+)_/);
    if (!match) continue;
    const studentId = match[1];

    const existing = index[studentId];
    if (!existing || file.getLastUpdated() > existing.getLastUpdated()) {
      index[studentId] = file;
    }
  }

  return index;
}

function isValidEmail_(value) {
  return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value);
}
